### ISSUE TITLE
[Bug] Respawning without a bed uses vanilla spawnpoint/randomization

### ISSUE THREAD

**Issue by RalphORama** [WiIIiam278/HuskHomes#442]
Steps to reproduce:

1. Install HuskHomes
2. Do **not** set a home/sleep in a bed
3. Use `/setworldspawn` in one location
4. Use `/setspawn` in another location
5. Use `/kill`
6. Respawn
7. You will respawn in an area around where `/setworldspawn` was executed instead of the exact coordinates of `/setspawn`

Instead of this happening, the player should be taken to the point where `/setspawn` was executed, similar to how Essentials' respawn mechanics work.

**Comment by WiIIiam278** [comment]
/setspawn also updates the world respawn position; HuskHomes doesn't carry execute a teleport on respawn as this is handled by the Vanilla Minecraft mechanics.

If I were to use a random teleport, the ability to customize through those mechanics would be lost (and spawn radius is a useful one!) You can set the respawn position radius through the `spawnRadius` gameRule.

**Comment by RalphORama** [comment]
Thanks for the info!
