### ISSUE TITLE
Thread.sleep() in MinecraftServer.tick()

### ISSUE THREAD

**Issue by foxii-cn** [WiIIiam278/HuskHomes#450]
So the whole server will lag for about 2 seconds every time a player logs in.
![IX(1ML JCDW(@W08IQU348I](https://github.com/WiIIiam278/HuskHomes/assets/38043552/85a98b7c-6af3-48d5-873b-02903a6201f7)
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">environment:</p>

environment | version
-- | --
Java | azul/prime:17
HuskHomes | 4.4.1
Fabric | 0.14.21
Minecraft | 1.20.1
redis | redis:7.0.11-alpine3.18

</body>
</html>

**Comment by WiIIiam278** [comment]
Seems like a quirk of one of the schedulers on fabric
