### ISSUE TITLE
[bug] ESS migration cannot migrate home with same name

### ISSUE THREAD

**Issue by hkkongou** [WiIIiam278/HuskHomes#456]
problem details:
with 2 server using essentials, if i want to migrate essentials homes to huskhome mysql with cross_server function. The position of the homes with same name between servers will be wiped and replaced with a newly import.

expected outcomes:
different server, same player's home with same name should have distinct data record, so that players data after migration, allow players to use the home on both of the servers.

video demonstration
https://youtu.be/RcS2nU8DboA

server 1 config
https://paste.denizenscript.com/View/111945
server 2 config
https://paste.denizenscript.com/View/111946

**Comment by WiIIiam278** [comment]
I'm a bit confused by your expected outcome -- HuskHomes home names are unique, and work cross server, so that players can teleport to their homes globally (across the bungee network). If the plugin supported non-unique names, it wouldn't work -- what should the player expect by typing the same home name?

If you want separate homes per-server, use separate database tables and distinct cluster IDs if you want multiple HuskHomes instances on one network. Note that you can't mix and match both cross-server TP and cross-server homes.

**Comment by hkkongou** [comment]
> I'm a bit confused by your expected outcome -- HuskHomes home names are unique, and work cross server, so that players can teleport to their homes globally (across the bungee network). If the plugin supported non-unique names, it wouldn't work -- what should the player expect by typing the same home name?


My current essentials set up is that each server have separate homes, but I want to merge all of these essentials homes on different servers into huskhomes, so that players can home tp across server.

> 
> If you want separate homes per-server, use separate database tables and distinct cluster IDs if you want multiple HuskHomes instances on one network. Note that you can't mix and match both cross-server TP and cross-server homes.

so you are saying that there is no way for huskhome to have cross server teleport to player's homes?(a server player home back to another server's home)?

**Comment by WiIIiam278** [comment]
> so you are saying that there is no way for huskhome to have cross server teleport to player's homes?(a server player home back to another server's home)?

There is; the plugin simply doesn’t support having multiple homes with the same name, as homes are global cross server. The import system isn’t designed to work that way.

**Comment by hkkongou** [comment]
> > so you are saying that there is no way for huskhome to have cross server teleport to player's homes?(a server player home back to another server's home)?
> 
> There is; the plugin simply doesn’t support having multiple homes with the same name, as homes are global cross server. The import system isn’t designed to work that way.

if is in that case , can I make a suggestions so that there can be a customized prefix add to all of the names imported? 
originally server 1 and 2 both have home name home1
migrate add custom prefix "s1_" to server 1 migration, so that the name becomes s1_home1, and server 2 become s2_home2

if thats too complicated , is it possible for me to migrate one server's data then add a prefix by SQL concat a prefix?

**Comment by WiIIiam278** [comment]
What you’re describing would work indeed with a manual bit of sql work

**Comment by WiIIiam278** [comment]
Closing as out of scope / specific user need
