### ISSUE TITLE
"error_already_teleporting" persists after teleportation completes on Folia

### ISSUE THREAD

**Issue by NewPixelDev** [WiIIiam278/HuskHomes#462]
Server system: Windows Server 2022 Datacenter
Server Core: Folia 【This server is running Folia version git-Folia-"daacd42" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: daacd42)
You are running the latest version
Previous version: git-Folia-"b5fc6d0" (MC: 1.20.1) 】
HuskHomes plugin version: 4.4.1-4.4.3 (both have problems)

Reproduce method:
I also have no clue, it's like HuskHomes is picking players at random.

can lead to the following problems:
Players selected by HuskHomes cannot use all the commands of HuskHomes, and these selected players will prompt "error_already_teleporting" information every time they input.

I have tried the following:
Let the players who are triggered by this BUG "suicide" or "exit the server and rejoin the server" can't solve it. Only restarting the server can solve it temporarily.
I even converted from SQLITE to Mysql, there is no way to fix

**Comment by WiIIiam278** [comment]
I think this might be caused by some wackiness:tm: with how Folia schedules stuff, as I can't repro on Paper, Fabric, etc. I'll continue to look into it, but do bare in mind Folia is alpha software for a reason

**Comment by NewPixelDev** [comment]
Ok, I hope you can solve this problem as soon as possible, thank you

**Comment by WiIIiam278** [comment]
Should be fixed by HuskHomes 4.6 (timed teleports are now properly canceled if they fail at the last hurdle)
