### ISSUE TITLE
When /rtp is disabled, no other plug-in can use /rtp

### ISSUE THREAD

**Issue by postyizhan** [WiIIiam278/HuskHomes#479]
hello, it's me again, tell me
>You can disable features by adding the command you wish to disable to the disabled_commands section of config.yml.
That is all~.

yes it works, but even if i disable /rtp other plugins still can't use /rtp, it will prompt

>That command is disabled!

I need to use the rtp of other plugins, I have my reasons, please reconsider `adding a switch for the functionality of the plugin`, thanks

Just to add, I can use pluginname:rtp to use other plugins, but my players don't like it, and they don't want to change the name of rtp

**Comment by WiIIiam278** [comment]
This feature works with Paper 1.19.4/1.20+ — please update you it version :)
