### ISSUE TITLE
folia: Teleportation seemingly applies fall damage when teleporting between different y-levels

### ISSUE THREAD

**Issue by Dr-WeiAL** [WiIIiam278/HuskHomes#483]
Takes abnormal fall damage when using some teleportation commands
First of all, the op won't be harmed by the fall
The steps that triggered the issue, as tested specifically, are as follows
1. Setting up "home 1"
2. Set up "home 2" 60 blocks away from "home 1" and make sure that the height difference will cause fall damage.
3. From "home" Teleport on high to "home" on low.
4. You should have fall damage by this point.

I have tested and found that /warp, /home, /spawn, /back cause this problem, /tpa does not.

Server-side: Folia version git-Folia-"f6e91e9" (MC: 1.20.1)

**Comment by nicolube** [comment]
Donno if that related, but re expience some similear deaths on reconnecets.

**Comment by Dr-WeiAL** [comment]
I think I know what's going on.
After I removed NoCheatPlus, the problem stopped happening, so I think it's a NoCheatPlus issue.

**Comment by WiIIiam278** [comment]
No cheat plus issue
