### ISSUE TITLE
Fabric 4.4.5-4.5 tp boat/horse bug

### ISSUE THREAD

**Issue by Unleashed75** [WiIIiam278/HuskHomes#496]
While sat in a boat or on a horse, the /home may not fully work.
I don't think it is teleporting the player at all, you just seem to fall through the world endlessly till you use the /back or redo the /home <name> commands.
Short video showing what I mean
https://drive.google.com/file/d/1S12Nb5hn4KXMZSttUWDH65qGy83dXyKZ/view

Other mods were installed when I first heard of this from another user but in this video I had removed all mods from the server and only have;
fabric-api-0.88.1+1.20.1
HuskHomes-Fabric-4.5
Installed on the server and the client is 100% vanilla.
The server was running HuskHomes-Fabric-4.4.5 when the player first told me about it, and I updated the server in hopes it fixed it and then tested with HuskHomes-Fabric-4.5 for the video.

I have not tested with other teleport commands, only what you see in the video.

**Comment by WiIIiam278** [comment]
probably need to add some checks to not let you teleport in those situations. fabric is complicated lol

**Comment by Unleashed75** [comment]
I do remember a couple versions back (not sure which) where I could teleport while sat in a boat with no problems. When teleporting back, it would take me back, just not in the boat, so I would start to sink under the boat which I was okay with.

Right now when it does work and teleport you out of the boat/horse to where you want to go, going back does place you back into the boat/horse which is also nice but I personally don't mind how you want to do it.
As long as you know :)
