### ISSUE TITLE
[Bug] Players spawning at bed when bed has been destroyed

### ISSUE THREAD

**Issue by RillSoji** [WiIIiam278/HuskHomes#504]
When a player breaks their bed and dies they respawn at their old bed loc instead of world spawn. Same for respawn anchors in the nether.

Running latest velocity and paper and have tested with v. 4.5, 4.5.1 and latest alpha build for huskhomes that was on modrinth. I have no other spawn controlling plugins installed. 

Yes worldspawn has been set and the spawn warp has been set. 

Configs are:
cross_server:
  enabled: true
  messenger_type: PLUGIN_MESSAGE
  cluster_id: ''
  global_spawn:
    enabled: true
    warp_name: Spawn
  global_respawning: true
 
 EDIT: v Found this issue's origins. Not husk related. Phew! 
_I can't confirm if this is related or not but it seems that after dying on a different server, any loaded nether portals stop allowing them through. The players have to travel to an unloaded nether portal to be able to enter the nether again which then causes all nether portals to function normally again._

**Comment by WiIIiam278** [comment]
Tested -- as stated in the OP, seems unrelated to HuskHomes :)
