### ISSUE TITLE
Revisiting Squaremap support

### ISSUE THREAD

**Issue by dchurch315** [WiIIiam278/HuskHomes#511]
As of 22 OCT 2023, it appears the maintainer for Pl3xmap has pulled it off Github and also all of the major plugin hosting sites such as Spigot and Modrinth. Assuming that this isn't a temporary decision (it had been reported previously that the developer was stopping work on it), will you revisit adding support for squaremap to the next major version of HuskHomes?

**Comment by WiIIiam278** [comment]
Huh, that's random. I think I'll wait for more information and maybe ask around myself. I'm not that big a fan of squaremap in general really. It was getting updates til just a few days ago, so this is weird.

**Comment by dchurch315** [comment]
If you should find any news, please mention as it has been difficult to find out what is really going on from BillyG.

**Comment by WiIIiam278** [comment]
I've done some research. Apparently Billy (also the former maintainer of Purpur) has left the Minecraft scene altogether. No real reason afaik, but they were involved in some (relatively light) drama in the Purpur discord the other day. The user “granny.dev” had stated they have been given repository rights to continue maintaining the plugin and are working to have the resource restored on Modrinth. The spigot page for PlexMap was never deleted (as that requires an administrator).

What this means for my stuff: I'm going to update the dependencies to use the new maintainers repository for now. I'm not going to immediately jump ship to Squaremap (for the second time) as SM forks the worse older PM, and provided this new maintainer does their job of keeping SM up to date I see no issue with the status quo.

Many thanks for your interest.
