### ISSUE TITLE
Command can not be executed correctly when use non-English arguments

### ISSUE THREAD

**Issue by CarmJos** [WiIIiam278/HuskHomes#537]
When users want to use non-English character in commands, it cannot function normally and notified this:

```text
The parameters should be separated by spaces, but adjacent data was found.
```

![DMHZ95{D4VY8E FKPOYKYBV](https://github.com/WiIIiam278/HuskHomes/assets/36306882/bfa73c3b-42e7-44f1-9f3c-355ecaf74168)

This is a big issue for non-English users, especially some servers that allow Chinese names to join and play.The failure of some commands to run will directly affect the key functions of the plugin(e.g. `/tpa`).

Also, plugin errors cannot be displayed to users, users are not understand why this command cannot be used.

**Comment by WiIIiam278** [comment]
That looks like a brigadier parsing error. Try disabling brigadier tab completion in your config and try again. Also make sure restrict names is turned off so it'll let users include UTF8 characters in home names

**Comment by CarmJos** [comment]
Well, in China, MineCraft is represented by NetEase, and most NetEase players use Chinese names, so I have to come here to raise this issue.

After following the solution you proposed, the problem was solved. **Thank you very much for your support!**
