### ISSUE TITLE
[Feature request] Limit the number of homes that can be accessed using permission

### ISSUE THREAD

**Issue by nhanledev** [WiIIiam278/HuskHomes#544]
**Scenario:**
- Player has a max home of 10
- Player sets all 10 homes
- Player's max home of 10 is revoked and set to max of 2
- Player can access the 10 homes

**Idea:**
- The player should not be able to access the previous home locations if the limit has been changed via permission.

**Comment by WiIIiam278** [comment]
Sorry, I'm not interested in accepting this request at this time :)
