### ISSUE TITLE
Feature suggestion /tpaall

### ISSUE THREAD

**Issue by AyalX** [WiIIiam278/HuskHomes#546]
Hey, I'd like to suggest a command to add which is `/tpaall` which sends a tpa request to all players to accept and get teleported. This command is avaliable on essentials and is good for admin's whenever they want to have some kind of drop or invite the entire server to a designated location instead of forcefully teleporting everyone.

**Comment by WiIIiam278** [comment]
Already a feature of HuskHomes - exactly as you describe
