### ISSUE TITLE
[Feature Request] Can "/back" be compatible with "RES TP" that supports Residence?

### ISSUE THREAD

**Issue by BangXi** [WiIIiam278/HuskHomes#547]
Can the "/back" of HuskHomes be adapted to the "res tp" that supports residence?

**Comment by WiIIiam278** [comment]
It can if you enable the option that listens to the TeleportEvent for updating the /back position. I don't wish to add manual hooks for every plugin, though; so I'm rejecting this specific request.

**Comment by BangXi** [comment]
> It can if you enable the option that listens to the TeleportEvent for updating the /back position. I don't wish to add manual hooks for every plugin, though; so I'm rejecting this specific request.

thank you❤️

**Comment by iVillager** [comment]
> Can the "/back" of HuskHomes be adapted to the "res tp" that supports residence?

You should ask this to the plugin developer :P
