### ISSUE TITLE
player can't accept tpa request from other server.

### ISSUE THREAD

**Issue by Ecilpse** [WiIIiam278/HuskHomes#560]
player can't accept tpa request from other server.
i tried reconnect or restart server but still same.
The settings of huskhomes and versions are all the same, and only the server.yml in the huskomes folder is different.

video: https://youtu.be/e7Rb807C6vY

**Comment by WiIIiam278** [comment]
Unable to reproduce. Likely a locale issue as the video demonstrates broken locales. Regenerate these.

**Comment by seeruk** [comment]
I've just been setting things up on a small Velocity network and have hit a similar issue. If I have both servers set up identically with the latest version available for Paper on 1.21.1 (admittedly an alpha release!), then using the pluginmsg API cross-server TPA doesn't seem to work - the other player just receives nothing, though I can autocomplete the TPA command just fine with player names that are on other servers. If I swap to use Redis instead, it all works fine. No other changes made, just swapping to Redis and it seems totally happy.

**Comment by WiIIiam278** [comment]
Is the bungee plugin messaging channel turned off on your velocity proxy?

**Comment by seeruk** [comment]
Aah interesting... it is, this is probably an issue because of ChatControl Red and VelocityControl in that case, apologies for misreporting. They promise in their setup that they handle it instead:

```
Set bungee-plugin-message-channel to false in your velocity.toml. Don't worry, if you have plugins utilizing this channel we will handle their data manually.
```
