### ISSUE TITLE
Add possibility to move during teleportation

### ISSUE THREAD

**Issue by Addos223** [WiIIiam278/HuskHomes#564]
As in title add the option in config to be able to move during teleportation to spawn or tpa

**Comment by WiIIiam278** [comment]
Could you clarify what you mean? I don't quite understand :) HuskHomes doesn't restrict movement - it simply cancels the TP _should_ you move.

**Comment by Addos223** [comment]
I mean that if I move it doesn't cancel the teleportation

**Comment by LovelyGuYiMeng** [comment]
I wanted to ask this as well, although The point of the warmup time is to prevent players moving away while in combat or PvE, not to annoy them. But it can still be added as an optional option
