### ISSUE TITLE
When the player ID suffix is "__" There will be bugs with TPA

### ISSUE THREAD

**Issue by BangXi** [WiIIiam278/HuskHomes#573]
When the player ID suffix is "__" 
example: eh.. , AAA__ , 123__ , BBB__
Use TPA requests to be sent to players
After the other party clicks Accept, an error appears
![图片](https://github.com/WiIIiam278/HuskHomes/assets/135555687/2183318c-a109-4790-9605-ed69b5f3ab9e)
In this case, consent can only be sent using the /tpaccept directive

1.20.4
huskhomes 4.6

**Comment by WiIIiam278** [comment]
Duplicate of #568
