### ISSUE TITLE
Unable to teleport player to myself

### ISSUE THREAD

**Issue by jhqwqmc** [WiIIiam278/HuskHomes#575]
When *player1* is using `/tp player2 player1`, it cannot trigger the transmission of *player2* to *player1*, and then when using `/tpall` and `/tpaall`, it prompts *Error: There are no players online who could teleport to you.*

**Comment by jhqwqmc** [comment]
[video](https://www.dropbox.com/scl/fi/kevoc33divzxyijpb3ndx/QQ2024220-171941-HD.mp4?rlkey=1gexo97sdkf6l5o083m52gsvk&dl=0)

**Comment by WiIIiam278** [comment]
Please regenerate your locale files
