### ISSUE TITLE
Player can not accept/deny tpa from others by clicking on chat-gui if its username has __ (double underscore)

### ISSUE THREAD

**Issue by nhanledev** [WiIIiam278/HuskHomes#587]
Scenario:
- Player 1 has name `abc___`
- Player 1 send tp request to other players
- Other players click on ACCEPT button on chat
- The plugin says that player `abc_\_` does not exists

**Comment by ProdPreva1l** [comment]
Duplicate #568

**Comment by nhanledev** [comment]
Duplicated
