### ISSUE TITLE
back protection

### ISSUE THREAD

**Issue by zwqwei** [WiIIiam278/HuskHomes#589]
Does /back have a protection function?

**Comment by WiIIiam278** [comment]
Please clarify what you mean by protection? :)

**Comment by zwqwei** [comment]
When I die in the lava /back will be passed back to the lava 0.0

**Comment by WiIIiam278** [comment]
Sounds like you're looking for teleport safety, which isn't a feature at the moment.

Duplicate of #36

**Comment by zwqwei** [comment]
So can you add this function? I've been troubled for a long time :(
