### ISSUE TITLE
After performing a reload on Pl3xMap, Pl3xMap does not display warp

### ISSUE THREAD

**Issue by MSCMDD** [WiIIiam278/HuskHomes#591]
After performing a reload on Pl3xMap, Pl3xMap does not display warp
![image](https://github.com/WiIIiam278/HuskHomes/assets/128666602/36d80a59-b0e9-463d-9e56-0d96bf9dfb8b)

**Comment by WiIIiam278** [comment]
Pl3xMap exposes the `Pl3xMapEnabledEvent`, which I listen to to handle the plugin's own reload routines (assuming you're using /pl3xmap reload, if that's a thing). If you're using PlugMan to reload a plugin, this isn't supported.
