### ISSUE TITLE
[Suggestion] Add the ability to translate date format

### ISSUE THREAD

**Issue by NoltoxGit** [WiIIiam278/HuskHomes#592]
Hello,
Is it possible to add the ability to translate the date format in plugin messages?
It currently looks like this: `Mar 17 2024, 19:50`.

And I'd like to be able to translate it to : `17/03/2024 - 19h50` for example.

**Comment by WiIIiam278** [comment]
Date time formats will now be based on your system locale.

**Comment by NoltoxGit** [comment]
> Date time formats will now be based on your system locale.

I've a big error with the latest build : https://mclo.gs/GoHyCOf
