### ISSUE TITLE
Change in the /edithome command

### ISSUE THREAD

**Issue by NoltoxGit** [WiIIiam278/HuskHomes#594]
Hello,
Would it be possible to add a safety feature to the command `/edithome (home) rename (newname)` so that it's not possible to rename a home if the name used, in order to avoid player confusion, please?

**Comment by WiIIiam278** [comment]
I've read your request a few times and don't understand it. What are you asking for?

**Comment by NoltoxGit** [comment]
> I've read your request a few times and don't understand it. What are you asking for?

I want to say: I've little problem, like if i've two homes named "Cave" and "House", if i type /edithome Cave rename House, the second home (named House at origin) will be cleared... So i ask for like a security to provided this from happening...

**Comment by WiIIiam278** [comment]
Disable overwrite_existing in your config

**Comment by NoltoxGit** [comment]
> Disable overwrite_existing in your config

It's only working with the `/sethome` command and not with the `/edithome` cmd :/
