### ISSUE TITLE
Bug with the /edithome commande

### ISSUE THREAD

**Issue by NoltoxGit** [WiIIiam278/HuskHomes#595]
Hello,
I just removed the `huskhomes.command.edithome.privacy` permission but they still see the subcommand displayed in auto-completion. 
Would it be possible to hide the subcommands when a player doesn't have the permissions please?

**Comment by WiIIiam278** [comment]
Fixed in [65cc90e](https://github.com/WiIIiam278/HuskHomes/commit/65cc90e79eb396ff70d8bac292238d9c255a5d33)
