### ISSUE TITLE
Jitpack authorization issue

### ISSUE THREAD

**Issue by ImNotStable** [WiIIiam278/HuskHomes#604]
```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve net.william278:huskhomes-paper:4.6.2.
     Required by:
         project :
      > Could not resolve net.william278:huskhomes-paper:4.6.2.
         > Could not get resource 'https://jitpack.io/net/william278/huskhomes-paper/4.6.2/huskhomes-paper-4.6.2.pom'.
            > Could not GET 'https://jitpack.io/net/william278/huskhomes-paper/4.6.2/huskhomes-paper-4.6.2.pom'. Received status code 401 from server: Unauthorized
```

I have the William278 repository properly setup, but I have another dependency that requires Jitpack which is causing this error.

**Comment by WiIIiam278** [comment]
Simply move the william278 repo higher up in your dependencies section

**Comment by ImNotStable** [comment]
Already tried that, it didn't work
![image](https://github.com/WiIIiam278/HuskHomes/assets/51060503/5e43f055-23a3-4e41-a76c-04fda6e97df7)

**Comment by ImNotStable** [comment]
![image](https://github.com/WiIIiam278/HuskHomes/assets/51060503/f1a5b0f7-382e-4645-9612-5aa1e8392011)

**Comment by WiIIiam278** [comment]
You're still targeting an invalid artifact.
It's net.william278.huskhomes:huskhomes-bukkit:4.6.2

**Comment by ImNotStable** [comment]
oops
