### ISSUE TITLE
v4.6.2 plugin cannot load in purpur1.17.1 latest build

### ISSUE THREAD

**Issue by sdgedghdg** [WiIIiam278/HuskHomes#607]
`as the title means`
[huskhome issus log.txt](https://github.com/WiIIiam278/HuskHomes/files/14886857/huskhome.issus.log.txt)

**Comment by WiIIiam278** [comment]
You upgraded from an older version and didn't regenerate your config file. Please delete your old HuskHomes config / messages files and restart your server

**Comment by sdgedghdg** [comment]
thanks a lot
