### ISSUE TITLE
[Suggestion] Add possibility to "silent" command

### ISSUE THREAD

**Issue by NoltoxGit** [WiIIiam278/HuskHomes#610]
Hello,

Is it possible to add a suffix to all commands so that they don't display messages to the player if they're executed by the console ?

Example:
`/huskhomes:spawn PLAYER -s` → The value `-s` after a command means that the player does not receive the result in the chat.

**Comment by WiIIiam278** [comment]
I think probably not. That's add a bunch of logical overheads for a use case probably better served by the API

**Comment by NoltoxGit** [comment]
> I think probably not. That's add a bunch of logical overheads for a use case probably better served by the API

Why I ask this ?
Because I'm from CMI, and this was one of the useful features there and I could teleport players by hiding the result of the command, and displaying another message instead (especially for warps).

**Comment by WiIIiam278** [comment]
I've decided to decline this feature request just due to it being too niche to support - thank you for the suggestion though.
