### ISSUE TITLE
The "TP" command does not seem to be registered properly.

### ISSUE THREAD

**Issue by tygh89071388** [WiIIiam278/HuskHomes#621]
HuskHomes 4.6.2

When I use /tp ID, it seems to only trigger the original command, which is minecraft:tp. I've tried the two methods on https://william278.net/docs/huskhomes/command-conflicts, but neither worked. However, /huskhomes:tp works fine.

**Comment by WiIIiam278** [comment]
hey there, there's nothing I can do about this unfortunately - it just happens on some setups. Try a command alias binding `minecraft:tp` -> `huskhomes:tp`

**Comment by tygh89071388** [comment]
> hey there, there's nothing I can do about this unfortunately - it just happens on some setups. Try a command alias binding `minecraft:tp` -> `huskhomes:tp`

Interestingly, following your method works, but using TAB for ID completion only shows players from the current server, not from other server.

**Comment by WiIIiam278** [comment]
Yes. Command aliases don't support tab completion--this is a known paper thing

**Comment by Huge-mistake** [comment]
At version 1.20.4, the 'tp' command of the 'huskhomes' plugin was working properly, but I encountered this issue after upgrading the server to version 1.20.6.

Can this issue be resolved by accessing https://github.com/PaperMC/Paper/pull/9971  ?

**Comment by WiIIiam278** [comment]
Yes. Until that PR is merged, there's no perfect solution to this issue.
