### ISSUE TITLE
Make `/tpignore` disable `/tp` and not just requests

### ISSUE THREAD

**Issue by Boy0000** [WiIIiam278/HuskHomes#631]
Handy for teams where you might not want someone with normal TP permission to be able to come
Alternatively add a secondary `/tptoggle` command

Ofc anyone with a bypass permission or something would be able to go through the toggle

**Comment by WiIIiam278** [comment]
Thought about this some more and decided that I don't want to introduce another command for this purpose, though may consider expanding/altering the configurability of /tpignore in the future. So going to close this for now and rethink.
