### ISSUE TITLE
Suggestion: Linking phomes in chat

### ISSUE THREAD

**Issue by FormulaAbyss** [WiIIiam278/HuskHomes#635]
Just had this idea as I saw people posting their phome as a full command:

'/phome myname.homename'

Thought it would be great if there was a way to link it in chat as a clickable button for everyone. (I realize with chat reporting, this might have some issues, but would definitely make chat look cleaner.)

**Comment by WiIIiam278** [comment]
Thanks for the request, though this is probably out of scope for a homes plugin :)
