### ISSUE TITLE
Players very often die in blocks at /rtp

### ISSUE THREAD

**Issue by kitovoi111** [WiIIiam278/HuskHomes#644]
Players very often die in blocks at /rtp, your plugin does not check for the presence of a block in the player, basically all my players are suffocating in the mountains.

**Comment by WiIIiam278** [comment]
Could you say which version and platform (spigot, fabric, paper, etc?) you are running

**Comment by ProdPreva1l** [comment]
Is that combined? or tested on?

**Comment by WiIIiam278** [comment]
Closing as invalid as user stated they are using their own fork of HuskHomes
