### ISSUE TITLE
/top command

### ISSUE THREAD

**Issue by n1ckoates** [WiIIiam278/HuskHomes#646]
A `/top` command that teleports you to the highest point at your current position would be great, and I think it would fit in nicely with the other teleportation commands.

**Comment by WiIIiam278** [comment]
Think WorldEdit may be a bit better for this job?

**Comment by n1ckoates** [comment]
To be clear, it wouldn't make a block at the highest point -- it would teleport you to the *current* highest block. So if you're in a cave, it puts you on the surface.

**Comment by WiIIiam278** [comment]
Thought about it some more, this isn't a feature I'd like to add to HuskHomes. Thanks for your interest, however.
