### ISSUE TITLE
Fabric Database updates not happening async on teleport

### ISSUE THREAD

**Issue by Squidistry** [WiIIiam278/HuskHomes#656]
Husk homes is seeming to have TPS spikes up to the 2500's. Here is the spark report:
https://spark.lucko.me/aExbsU7JwV
Has something to do with databases even though I don't use one, or maybe something else so I'm not sure, just read what the methods were that are causing it.

**Comment by WiIIiam278** [comment]
Thanks for the report. Seems like something isn't firing async correctly.

**Comment by WiIIiam278** [comment]
Should be fixed.
