### ISSUE TITLE
Edit home and tp request in chat cant be use 

### ISSUE THREAD

**Issue by SnivyJ** [WiIIiam278/HuskHomes#659]
Hi

Edit home and tp request in chat cant be use , The mouse has no response whether hovering or clicking .
There are no errors in the console , This issue occurred when updating to 1.21

![1](https://github.com/user-attachments/assets/e1d1599d-ad24-4a7c-9f9d-b8e3a0499a6c)
![2](https://github.com/user-attachments/assets/d9571ade-5058-4bff-97e9-17ad9219d8a1)

**Java Env** OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
**Minecraft Server Version** CraftBukkit version 4263-Spigot-491f367-bed1e3f (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)
**Plugins Version** HuskHomes | v4.7
**Plugins List** PlaceholderAPI, ProtectFarmLand, LagFixer, CustomPlaceholder, Dongmuleather, TrChat, AutoRespawn, ViaVersion, ProtectItemFrame, TreeFeller, eBackup, ViaBackwards, LuckPerms, WTF, SbPlaceholder, ProtocolLib, GSit, Vault, dynmap, DecentHolograms, EpicRename, XConomy, PlayerPoints, Multiverse-Core, KeepInventory, DeluxeHub, Essentials, EssentialsProtect, HuskHomes, BungeeTabListPlus, PlugManX (PlugMan)

**Comment by WiIIiam278** [comment]
You are using CraftBukkit. Stop using CraftBukkit and move to Paper ASAP.

Adventure-Platform-Bukkit hasn't updated yet to provide compat for older versions, hence this won't work.
