### ISSUE TITLE
Using home on 1.20.6 or 1.21 may cause server crashes

### ISSUE THREAD

**Issue by buildin1** [WiIIiam278/HuskHomes#669]
[统计.txt](https://github.com/user-attachments/files/16508140/default.txt)
This is all the crash reports I have collected, and it can be seen that every time I use Home, it causes the server to crash

Folia1.20.6/1.21

**Comment by WiIIiam278** [comment]
Duplicate of #633.

Folia is still experimental.

**Comment by buildin1** [comment]
But this error keeps causing the server to crash, is there any solution
