### ISSUE TITLE
Unable to display player's home correctly

### ISSUE THREAD

**Issue by XXJNOTFOUND** [WiIIiam278/HuskHomes#689]
First of all, and this is just for me alone, let me make it clear that the server is not reporting any errors, and maybe this issue is hard to fix, and for that I apologize!

Let's say I'm a player with the name iXiangPro, with * permissions, and I create a new home (as shown in the picture)
![image](https://github.com/user-attachments/assets/c457d192-6e54-4b63-9847-4559f4d91c3c)

Successfully use /sethome Test to set up a home named Test
![image](https://github.com/user-attachments/assets/9e30baf3-32df-45e1-93f9-1ffdb97d63d9)

But when I type /homes or /homelist, it doesn't show any of my homes
![image](https://github.com/user-attachments/assets/675b67c8-6ddb-4454-9974-f2ce70512ee3)

But when you use /home <Tab Completion>, he will show your home
![image](https://github.com/user-attachments/assets/e93ee279-940c-4007-9441-b7e9ff72f336)

Other functions such as /warps & /phomes work fine, this error only happens to me and is specific to `home`.

It also looks like this when adding the hud extension
I tried switching accounts but everything works fine
It works for other players, but why not just me?

**Comment by XXJNOTFOUND** [comment]
Added: I'm using the latest beta version,not a old version

**Comment by XXJNOTFOUND** [comment]
```
[21:49:40 INFO]: Checking version, please wait...
[21:49:42 INFO]: Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-2280-930003b (MC: 1.21)
```

**Comment by WiIIiam278** [comment]
HuskHomesGUI is no longer supported. Please remove this plugin - you will need to find an alternative GUI add-on. Thanks
