### ISSUE TITLE
[Feature Request]After the server restarts, reset the /tpignore status

### ISSUE THREAD

**Issue by Huge-mistake** [WiIIiam278/HuskHomes#693]
I don't want to allow the use of /tpignore, because it is available by default and I didn't prohibit it at the beginning(It's my fault). Now some players have already used the /tpignore command to enable the ignore status, and I need a regret pill.

Can an option be added for this, such as resetting the existing /tpignore status after the server restarts and no longer saving it?
Or when a player exits the server/proxy server, the /tpignore status will be reset, this option is also very good.

I prefer the first one, but both seem to solve my problem.

**Comment by WiIIiam278** [comment]
Hey there, your best bet is to perform an UPDATE statement on your database users table which sets the tpignore state to FALSE for * (all users)
