### ISSUE TITLE
[feature request] support warm up timer in `/tp` command

### ISSUE THREAD

**Issue by izrin96** [WiIIiam278/HuskHomes#709]
can warm up timer to be included in `/tp` command as well? just like EssentialsX's `/tp`.

**Comment by WiIIiam278** [comment]
Thanks for your comment,

I decided against this for simplicity's sake. `/tp` is considered an admin command, and the warmup feature is intended to limit the power of instant teleportation abuse in gameplay.

Adding this would also be inconsistent with `/tphere`, and adding it for that command as well would be bad user experience - the teleporting user would get no warning of their need to stand still.
