### ISSUE TITLE
No importers are currently available

### ISSUE THREAD

**Issue by aeonshard** [WiIIiam278/HuskHomes#716]
I want to import EssentialsX Data but i get always a message with: 
[09:04:18 INFO]: Error: No importers are currently available. Please check the plugin docs for more details.

paper version: Paper 1.21.1-131, EssentialsX Version: Essentials v2.21.0-dev+121-f7a8f86, HuskHomes v4.8.

**Comment by WiIIiam278** [comment]
Already fixed as of... one minute before you posted the issue 😅.

https://github.com/WiIIiam278/HuskHomes/commit/964bca613095de4cec55da11d92ede604d5609b2
