### ISSUE TITLE
The teleportation has encountered an issue.

### ISSUE THREAD

**Issue by CCjun6** [WiIIiam278/HuskHomes#721]
When player A uses the command /tpa to player B, this issue occurs while they are on different sub-servers.
![image](https://github.com/user-attachments/assets/474b5c50-7e07-4d3c-ad4b-5b9628b4804e)
![image](https://github.com/user-attachments/assets/317aa437-0446-4918-bead-9862a99c5f48)

**Comment by WiIIiam278** [comment]
Check the troubleshooting section, this can occur in improperly configured offline mode setups. For further help you may wish to join our Discord.
