### ISSUE TITLE
Crash when update 4.8.2 -> 4.8.3 

### ISSUE THREAD

**Issue by FSOL-XDAG** [WiIIiam278/HuskHomes#734]
On paper 1.21.3, HuskHomes 4.8.2 works fine.

When updating to 4.8.3, it's crash.

Here is log : 

[latest.log](https://github.com/user-attachments/files/18171325/latest.log)

**Comment by WiIIiam278** [comment]
As per the change notes you must regenerate your config file when upgrading to 4.8.3 due to config changes 😄

> To update, please regenerate your config file. This means making a backup of your config.yml file somewhere, deleting it, and allowing the plugin to regenerate it, after which you can repopulate it with your settings.

**Comment by FSOL-XDAG** [comment]
Oh my God!!! As the previous updates went through without any external intervention, I thought it was the same for this update since it's a minor version (4.8.x). I should have looked before opening an issue. Thanks for your reply and congratulations on your work, which is much appreciated.
