### ISSUE TITLE
Can I turn off the function of RTP?

### ISSUE THREAD

**Issue by hexiruofeng** [WiIIiam278/HuskHomes#742]
I don't want it to register RTP commands. 3-

Config：
rtp:
  region:
    min: 500
    max: 5000
  distribution_mean: 0.75
  distribution_standard_deviation: 2.0
  restricted_worlds:
  - world_nether
  - world_the_end
  cross_server: false
  random_target_servers:
    server:
    - world
    - world_nether
    - world_the_end

**Comment by WiIIiam278** [comment]
Yes. Simply add `/rtp` to your list of `disabled_commands` at the bottom of the config file.
